### ISSUE TITLE
popups does not work

### ISSUE THREAD

**Issue by jimbok8** [JPro-one/JPro-Samples#1]
I am running gradlew popups:jproRun and get the following errors:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/kayji/.gradle/caches/modules-2/files-2.1/c
om.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,by
te[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[error] c.j.i.c.InstanceImpl - Error while starting application:
java.lang.NoClassDefFoundError: com/sun/javafx/css/StyleConverterImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:713)
        at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:708)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:721)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.StyleConverterImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:713)
        at java.base/jdk.internal.loader.BuiltinClassLoader$4.run(BuiltinClassLoader.java:708)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
[warn] c.j.i.c.InstanceImpl - Application didn't show the stage. JPro is now calling show()
[error] c.j.i.s.ViewSerializerActor - JavaFXStreamer - got Exception:
java.lang.NullPointerException: null
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:18)
        at com.jpro.internal.communicator.ViewImpl.<init>(ViewImpl.scala:87)
        at com.jpro.internal.communicator.ViewImpl.<init>(ViewImpl.scala:29)
        at com.jpro.internal.server.ViewByActor.<init>(ViewSerializerActor.scala:81)
        at com.jpro.internal.server.ViewSerializerActor$$anonfun$receive$1$$anonfun$applyOrElse$1.$anonfun$applyOrElse$2(ViewSerializerActor.scala:49)

        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.util.Predef$.$anonfun$runInAndBlock$1(Predef.scala:184)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
java.lang.NullPointerException: Can't access extension-class for null
        at simplefx.macros.Extension$.setRef(Extension.scala:72)
        at simplefx.scene.packageTrait$.toSceneExtension(packageTraitScene.scala:15)
        at simplefx.scene.packageTrait$ImportTrait.toSceneExtension(packageTraitScene.scala:15)
        at simplefx.scene.packageTrait$ImportTrait.toSceneExtension$(packageTraitScene.scala:15)
        at simplefx.all$.toSceneExtension(all.scala:5)
        at com.jpro.meta.stream.FXSerializerImpl.transferScene(FXSerializer.scala:102)
        at com.jpro.meta.stream.FXAppSerializer.$anonfun$new$6(FXAppSerializer.scala:39)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLikeAlternateSignature.$anonfun$$minus$minus$greater$1(CoreTypesEvent.scala:16)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$2(CoreTypesBindable.scala:192)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$1(CoreTypesBindable.scala:191)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.trigger(CoreTypesBindable.scala:190)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater(CoreTypesEvent.scala:25)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater$(CoreTypesEvent.scala:25)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$minus$minus$greater(CoreTypesBindable.scala:24)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLikeAlternateSignature.$minus$minus$greater(CoreTypesEvent.scala:16)
        at com.jpro.meta.stream.FXAppSerializer.$anonfun$new$5(FXAppSerializer.scala:39)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runWhenever$2(CoreTimeEvent.scala:133)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runWhenever$2$adapted(CoreTimeEvent.scala:133)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$triggerOnChange$3(CoreTypesBindable.scala:208)
        at simplefx.cores.standard.parts.CoreScheduler.runSchedulerImpl(CoreScheduler.scala:73)
        at simplefx.cores.standard.parts.CoreScheduler.runSchedulerImpl$(CoreScheduler.scala:52)
        at simplefx.cores.standard.Core.runSchedulerImpl(Core.scala:9)
        at simplefx.cores.standard.parts.CoreScheduler.tryStartSchedulerStop(CoreScheduler.scala:44)
        at simplefx.cores.standard.parts.CoreScheduler.tryStartSchedulerStop$(CoreScheduler.scala:42)
        at simplefx.cores.standard.Core.tryStartSchedulerStop(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$IEventEmitter.emit(CoreTypesEvent.scala:64)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$IEventEmitter.emit$(CoreTypesEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.emit(CoreTypesBindable.scala:24)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$IEventEmitter.emit$mcZ$sp(CoreTypesEvent.scala:64)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$IEventEmitter.emit$mcZ$sp$(CoreTypesEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.emit$mcZ$sp(CoreTypesBindable.scala:24)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl$mcZ$sp.setValue$mcZ$sp(CoreTypesBindable.scala:103)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl$mcZ$sp.setValue$mcZ$sp(CoreTypesBindable.scala:88)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl$mcZ$sp.setValue(CoreTypesBindable.scala:88)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl$mcZ$sp.setValue(CoreTypesBindable.scala:24)
        at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq(CoreTypesBindable.scala:150)
        at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq$(CoreTypesBindable.scala:149)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$colon$eq(CoreTypesBindable.scala:24)
        at com.jpro.internal.communicator.ViewImpl.$anonfun$new$1(ViewImpl.scala:56)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
        at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
        at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
        at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:509)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:502)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:326)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:834)
[info] c.j.m.s.Util$ - WORKAROUND! setting XY for Window because current XY is NaN

I am running gradlew.bat having pre-appended this line:
set JAVA_HOME=D:\Programs\JAVA\jdk-11.0.3.7-hotspot

The browser is chrome:
Google Chrome | 76.0.3809.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS | Windows 7 Service Pack 1 (Build 7601.24511)
JavaScript | V8 7.6.303.29
Flash | 32.0.0.255 C:\Users\kayji\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.255\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --flag-switches-begin --flag-switches-end

The other two samples run OK, as does HelloJPro

**Comment by FlorianKirmaier** [comment]
Thank you for opening the ticket!
We've fixed it now.
